### ISSUE TITLE
calculation error?

### ISSUE THREAD

**Issue by sashaman** [projazzka/jazzy-forms-dev#20]
is it me or? 
my formula: 

28.80 + (2_width + 2_height)    this ends in the wrong result 108.83333333333333

so i tried, just to be sure its not me, 

28.80 + 2_20 + 2_20    this ALSO ends in the wrong result 108.83333333333333

in the end i have tried lotta different variations of the formula and somehow all results are incorrect :(
lookin 4ward,
best regards
alex

**Comment by projazzka** [comment]
Well, this one is really an embarrassing one! Thanks a lot for reporting it, Alex.

FIxed in 5d6f0348c357bc3f3a78560cfca86013e477c2cb

At one point (related to the result precision) in the Javascript code I've taken "^" for the exponentiation operator, but in Javascript that's XOR. Awkward.

The fix will be available in the v0.9.2 update, tentatively scheduled for next week.
Igor
